# Generated by Django 3.1.4 on 2021-01-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lojas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
